HW2
================
Gunnar
10/3/2021

Loading libraries

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

*Problem 1* Part 1. Loading Mr. Trash Wheel dataset filtering out row
totals cleaning variable names and removing unnecssary variables
rounding sport balls to the nearest integer

``` r
library(readxl)
df <- read_excel("working data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "Mr. Trash Wheel")
```

    ## New names:
    ## * `` -> ...15
    ## * `` -> ...16
    ## * `` -> ...17

``` r
df <- df %>%
  filter(!endsWith(Month, "Total")) %>%
  clean_names() %>%
  select(-x15, -x16, -x17) %>%
  mutate(sports_balls = round(sports_balls))

df %>%
  nrow()
```

    ## [1] 344

``` r
df %>%
  pull(sports_balls) %>%
  head()
```

    ## [1] 7 5 6 6 7 5

``` r
df %>%
  group_by(year) %>%
  summarize(mean(chip_bags))
```

    ## # A tibble: 6 × 2
    ##    year `mean(chip_bags)`
    ##   <dbl>             <dbl>
    ## 1  2014             1610.
    ## 2  2015             1849.
    ## 3  2016             2752.
    ## 4  2017             2237.
    ## 5  2018             1279.
    ## 6  2019              930.

Part 2. Importing 2018 and 2019 data sets Remove first row of data Add
year variable to each data frame Omit rows with missing precipitation
data Omit total row for each df

``` r
df_p2019 <- read_excel("working data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2019 Precipitation", skip = 1)

df_p2019 <- df_p2019 %>%
  clean_names %>%
  mutate(year = 2019) %>%
  filter(!is.na(total)) %>%
  filter(!is.na(month))

df_p2018 <- read_excel("working data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2018 Precipitation", skip = 1)  

df_p2018 <- df_p2018 %>%
  clean_names %>%
  mutate(year = 2018) %>%
  filter(!is.na(total)) %>%
  filter(!is.na(month))

df_p_combined <- bind_rows(df_p2018, df_p2019) %>%
  mutate(month = month.name[month])


df_p_combined %>%
  group_by(year) %>%
  summarise(mean(total))
```

    ## # A tibble: 2 × 2
    ##    year `mean(total)`
    ##   <dbl>         <dbl>
    ## 1  2018          5.86
    ## 2  2019          2.78

``` r
nrow(df_p_combined)
```

    ## [1] 18

Part 3.

For the Mr. Trash Wheels data set, there were 344 observations spanning
between 2014 and 2019. In 2015, there was a mean of 1849 chip bags found
in a dumpster while in 2019 there was a mean of only 930.

For the combined precipitation data set, there were 18 observations
throughout 2018 and 2019. In 2018, the mean amount of precipitation was
5.86 inches while the mean amount of precipitation was 2.78 inches in
2019.

*Problem 2* Loading pols-month.csv, unemployment.csv, and snp.csv

``` r
pols_df <- read_csv("working data/fivethirtyeight_datasets/pols-month.csv")
```

    ## Rows: 822 Columns: 9

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemploy_df <- read_csv("working data/fivethirtyeight_datasets/unemployment.csv")
```

    ## Rows: 68 Columns: 13

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df <- read_csv("working data/fivethirtyeight_datasets/snp.csv")
```

    ## Rows: 787 Columns: 2

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Cleaning pols\_month dataframe

``` r
pols_df <- pols_df %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = month.name[month]) %>%
  mutate(prez = ifelse(prez_gop == 1, "gop", ifelse(prez_dem == 1, "dem", NA))) %>%
  select(year, month, -prez_gop, -prez_dem, -day)

names(pols_df)
```

    ## [1] "year"  "month"

Cleaning snp dataframe

``` r
snp_df <- snp_df %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = month.name[month]) %>%
  select(year, month, -day)
```

    ## Warning: Expected 3 pieces. Missing pieces filled with `NA` in 787 rows [1, 2,
    ## 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].

``` r
names(snp_df)
```

    ## [1] "year"  "month"

Cleaning unemployment dataframe

``` r
unemploy_df <- unemploy_df %>%
  clean_names() %>%
  pivot_longer(cols = jan:dec, names_to = "month") %>%
  select(year, month)

names(unemploy_df)
```

    ## [1] "year"  "month"

Merging the data sets

``` r
pols <- full_join(pols_df, snp_df)
```

    ## Joining, by = c("year", "month")
